spring.application.name=stockmanager

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/stock_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:sua-chave-secreta-stockmanager-minimo-32-caracteres}